version: "3"

networks:
  forgejo:
  proxy:
    external: true
    name: traefik

services:
  server:
    image: codeberg.org/forgejo/forgejo:1.20
    env_file:
      - .env
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=db:5432
      - FORGEJO__database__NAME=${DB_NAME}
      - FORGEJO__database__USER=${DB_USER}
      - FORGEJO__database__PASSWD=${DB_PASS}
    networks:
      - forgejo
      - proxy
    volumes:
      - forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    labels:
      - "traefik.http.routers.forgejo.rule=Host(`git.school.supercrafter100.com`)"
      - "traefik.http.services.forgejo.loadbalancer.server.port=3000"
      - "traefik.http.routers.forgejo.tls=true"
      - "traefik.http.routers.forgejo.tls.certresolver=letsencrypt"
      - "traefik.http.routers.forgejo.entrypoints=websecure"
      - "traefik.docker.network=traefik"

  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - forgejo
    volumes:
      - forgejo-postgress:/var/lib/postgresql/data

volumes:
  forgejo-postgress:
  forgejo: