entryPoints:
  web:
    address: ":80"
    # http:
    #   redirections:
    #     entrypoint:
    #       to: websecure
    #       scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: stijn.voeten01@student.ap.be
      storage: acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    network: traefik

api:
  dashboard: true

metrics:
  influxDB:
    address: influxdb:8086
    protocol: http
    database: traefik
    username: traefik
    password: o1K55zydh5Vl
    addRoutersLabels: true

tracing:
  zipkin:
    httpEndpoint: http://zipkin:9411/api/v2/spans

accessLog:
  filePath: "/var/log/traefik/access.log"
