entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: stijn.voeten01@student.ap.be
      storage: acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    network: traefik

api:
  dashboard: true
