version: "3"
services:
  influxdb:
    image: influxdb:2.7-alpine
    volumes:
      - database:/var/lib/influxdb2
    env_file:
      - .env
    expose:
      - 8086/udp
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${ADMIN_PW}
      - DOCKER_INFLUXDB_INIT_ORG=${ADMIN_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${SYSTEM_BUCKET}
    networks:
      - proxy
    labels:
      - "traefik.http.routers.influxdb.rule=Host(`metrics.school.supercrafter100.com`)"
      - "traefik.http.services.influxdb.loadbalancer.server.port=8086"
      - "traefik.http.routers.influxdb.tls=true"
      - "traefik.http.routers.influxdb.tls.certresolver=letsencrypt"
      - "traefik.http.routers.influxdb.entrypoints=websecure"
      - "traefik.docker.network=traefik"

volumes:
  database:

networks:
  proxy:
    external: true
    name: traefik
  